### ISSUE TITLE
Temporary build file to ignore

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/coding-blog-boilerplate#6]
When executing `codedoc build`, there is a temporary file created in `.codedoc/` with some randomness in its name.  For example, I have seen it called `__tmp_cgulce.js` and `__tmp_oglea.js`.

It suffices to ignore this file via `.gitignore` with the entry `.codedoc/__tmp_*`.

I can provide a PR to add this to the `.gitignore` file if desired.

**Comment by loreanvictor** [comment]
> I can provide a PR to add this to the .gitignore file if desired.

yes that would be great!
